a = int(input('Insira um valor para a: '))
b = int(input('Insira um valor para b: '))
c = int(input('Insira um valor para c: '))
d = int(input('Insira um valor para d: '))
e = int(input('Insira um valor para e: '))
f = int(input('Insira um valor para f: '))

x = (c * e) - (b * f) / (a * e) - (b * d)
y = (a * f) - (c * d) / (a * e) - (b * d)

print('\n======================')
print(f'{a}x + {b}y = {c}')
print(f'{d}x + {e}y = {f}')
print('======================\n')
print(f'x = {x}, y = {y}')
